// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CategoriesPageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Categories page", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Categories.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
    await testRunner.GivenAsync("I am logged in and on the categories page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Categories.feature.ndjson", 25);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Categories page is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Categories page is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task CategoriesPageIsDisplayed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Categories page is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table1.AddRow(new string[] {
                            ".categories-header h1",
                            "h1",
                            "",
                            "Категорії"});
                table1.AddRow(new string[] {
                            "#categories-list",
                            "div",
                            "",
                            ""});
                table1.AddRow(new string[] {
                            "#open-add-category-modal-btn",
                            "button",
                            "",
                            ""});
#line 9
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table1, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Open and close the add category modal")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Open and close the add category modal")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task OpenAndCloseTheAddCategoryModal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Open and close the add category modal", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table2.AddRow(new string[] {
                            "#open-add-category-modal-btn"});
#line 18
    await testRunner.WhenAsync("click elements", ((string)(null)), table2, "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table3.AddRow(new string[] {
                            "#form-add-category",
                            "true"});
#line 21
    await testRunner.ThenAsync("check elements visibility", ((string)(null)), table3, "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table4.AddRow(new string[] {
                            "#js-close-category-modal"});
#line 24
    await testRunner.WhenAsync("click elements", ((string)(null)), table4, "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table5.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 27
    await testRunner.ThenAsync("check elements class", ((string)(null)), table5, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Add category form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add category form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty", "", "#btn-submit-category", "click", "Вкажіть назву категорії", "2", null, DisplayName="Add category form validation - <Case>(empty,,#btn-submit-category,click,Вкажіть н" +
            "азву категорії,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("101 chars", "{chars:101}", "#category-name", "blur", "Назва має бути не довше 100 символів", "3", null, DisplayName="Add category form validation - <Case>(101 chars,{chars:101},#category-name,blur,Н" +
            "азва має бути не довше 100 символів,3)")]
        public async global::System.Threading.Tasks.Task AddCategoryFormValidation_Case(string @case, string name, string triggerLocator, string triggerAction, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Case", @case);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("TriggerLocator", triggerLocator);
            argumentsOfScenario.Add("TriggerAction", triggerAction);
            argumentsOfScenario.Add("Error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add category form validation - <Case>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.GivenAsync("I open the add category modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table6.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            string.Format("{0}", name)});
                table6.AddRow(new string[] {
                            string.Format("{0}", triggerLocator),
                            string.Format("{0}", triggerAction),
                            ""});
#line 37
    await testRunner.WhenAsync("fill form", ((string)(null)), table6, "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table7.AddRow(new string[] {
                            "#form-add-category .form-group:has(#category-name) span.form-error-text",
                            "span",
                            "",
                            string.Format("{0}", error)});
#line 41
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table7, "Then ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Enabled"});
                table8.AddRow(new string[] {
                            "#btn-submit-category",
                            "false"});
#line 44
    await testRunner.AndAsync("check elements state", ((string)(null)), table8, "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table9.AddRow(new string[] {
                            "#form-add-category",
                            "true"});
#line 47
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Category name of exactly 100 characters is valid")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Category name of exactly 100 characters is valid")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task CategoryNameOfExactly100CharactersIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Category name of exactly 100 characters is valid", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.GivenAsync("I open the add category modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table10.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{chars:100}"});
                table10.AddRow(new string[] {
                            "#category-name",
                            "blur",
                            ""});
#line 58
    await testRunner.WhenAsync("fill form", ((string)(null)), table10, "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Enabled"});
                table11.AddRow(new string[] {
                            "#btn-submit-category",
                            "true"});
#line 62
    await testRunner.ThenAsync("check elements state", ((string)(null)), table11, "Then ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table12.AddRow(new string[] {
                            "#form-add-category .form-group:has(#category-name) span.form-error-text",
                            "false"});
#line 65
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table12, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Select a category color (<Color>)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Select a category color (<Color>)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#10B981", "5", null, DisplayName="Select a category color (<Color>)(#10B981,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#EF4444", "6", null, DisplayName="Select a category color (<Color>)(#EF4444,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#F59E0B", "7", null, DisplayName="Select a category color (<Color>)(#F59E0B,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#8B5CF6", "8", null, DisplayName="Select a category color (<Color>)(#8B5CF6,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#EC4899", "9", null, DisplayName="Select a category color (<Color>)(#EC4899,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#06B6D4", "10", null, DisplayName="Select a category color (<Color>)(#06B6D4,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#84CC16", "11", null, DisplayName="Select a category color (<Color>)(#84CC16,11)")]
        public async global::System.Threading.Tasks.Task SelectACategoryColorColor(string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Select a category color (<Color>)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 72
    await testRunner.GivenAsync("I open the add category modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.WhenAsync(string.Format("click element \".color-swatch-btn[data-color=\'{0}\']\"", color), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table13.AddRow(new string[] {
                            string.Format(".color-swatch-btn[data-color=\'{0}\']", color),
                            "active",
                            "true"});
                table13.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#2563EB\']",
                            "active",
                            "false"});
#line 74
    await testRunner.ThenAsync("check elements class", ((string)(null)), table13, "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedValue"});
                table14.AddRow(new string[] {
                            "#category-color",
                            string.Format("{0}", color)});
#line 78
    await testRunner.AndAsync("check elements value", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Successfully add a new category with color <Color>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successfully add a new category with color <Color>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#2563EB", "12", null, DisplayName="Successfully add a new category with color <Color>(#2563EB,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("#EF4444", "13", null, DisplayName="Successfully add a new category with color <Color>(#EF4444,13)")]
        public async global::System.Threading.Tasks.Task SuccessfullyAddANewCategoryWithColorColor(string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully add a new category with color <Color>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 95
    await testRunner.GivenAsync("I open the add category modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table15.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{unique}"});
                table15.AddRow(new string[] {
                            string.Format(".color-swatch-btn[data-color=\'{0}\']", color),
                            "click",
                            ""});
                table15.AddRow(new string[] {
                            "#btn-submit-category",
                            "click",
                            ""});
#line 96
    await testRunner.WhenAsync("fill form", ((string)(null)), table15, "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table16.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 101
    await testRunner.ThenAsync("check elements class", ((string)(null)), table16, "Then ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table17.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\')",
                            "true"});
#line 104
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table17, "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table18.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\') .category-color-dot",
                            "style",
                            string.Format("{0}", color)});
#line 107
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table18, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Edit button is displayed for a category")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Edit button is displayed for a category")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task EditButtonIsDisplayedForACategory()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit button is displayed for a category", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 120
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table19.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'Salary\') .category-edit-btn",
                            "button",
                            "",
                            ""});
#line 121
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table19, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Edit modal is prefilled with the category data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Edit modal is prefilled with the category data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task EditModalIsPrefilledWithTheCategoryData()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit modal is prefilled with the category data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 125
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 126
    await testRunner.GivenAsync("I have created a category \"{unique}\" with color \"#EF4444\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 127
    await testRunner.AndAsync("I open the edit modal for category \"{unique}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedValue"});
                table20.AddRow(new string[] {
                            "#category-name",
                            "{unique}"});
                table20.AddRow(new string[] {
                            "#category-color",
                            "#EF4444"});
#line 128
    await testRunner.ThenAsync("check elements value", ((string)(null)), table20, "Then ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table21.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#EF4444\']",
                            "active",
                            "true"});
                table21.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#2563EB\']",
                            "active",
                            "false"});
#line 132
    await testRunner.AndAsync("check elements class", ((string)(null)), table21, "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table22.AddRow(new string[] {
                            "#category-submit-text",
                            "span",
                            "",
                            "Зберегти"});
#line 136
    await testRunner.AndAsync("check elements existence", ((string)(null)), table22, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Successfully edit category name and color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successfully edit category name and color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task SuccessfullyEditCategoryNameAndColor()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully edit category name and color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 140
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 141
    await testRunner.GivenAsync("I have created a category \"{unique}\" with color \"#2563EB\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 142
    await testRunner.AndAsync("I open the edit modal for category \"{unique}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table23.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{unique} updated"});
                table23.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#8B5CF6\']",
                            "click",
                            ""});
                table23.AddRow(new string[] {
                            "#btn-submit-category",
                            "click",
                            ""});
#line 143
    await testRunner.WhenAsync("fill form", ((string)(null)), table23, "When ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table24.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 148
    await testRunner.ThenAsync("check elements class", ((string)(null)), table24, "Then ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table25.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique} updated\') .categories-item-t" +
                                "itle span",
                            "span",
                            "",
                            "{unique} updated"});
#line 151
    await testRunner.AndAsync("check elements existence", ((string)(null)), table25, "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table26.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\') .category-color-dot",
                            "style",
                            "#8B5CF6"});
#line 154
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table26, "And ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedCount"});
                table27.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\')",
                            "1"});
#line 157
    await testRunner.AndAsync("check elements count", ((string)(null)), table27, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Edited category persists after page reload")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Edited category persists after page reload")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task EditedCategoryPersistsAfterPageReload()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edited category persists after page reload", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 161
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 162
    await testRunner.GivenAsync("I have created a category \"{unique}\" with color \"#2563EB\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
    await testRunner.AndAsync("I open the edit modal for category \"{unique}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table28.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{unique} updated"});
                table28.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#10B981\']",
                            "click",
                            ""});
                table28.AddRow(new string[] {
                            "#btn-submit-category",
                            "click",
                            ""});
#line 164
    await testRunner.WhenAsync("fill form", ((string)(null)), table28, "When ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table29.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 169
    await testRunner.AndAsync("check elements class", ((string)(null)), table29, "And ");
#line hidden
#line 172
    await testRunner.AndAsync("the page is reloaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table30.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique} updated\')",
                            "true"});
#line 173
    await testRunner.ThenAsync("check elements visibility", ((string)(null)), table30, "Then ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table31.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique} updated\') .category-color-do" +
                                "t",
                            "style",
                            "#10B981"});
#line 176
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table31, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cancelling the edit modal does not change the category")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cancelling the edit modal does not change the category")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        public async global::System.Threading.Tasks.Task CancellingTheEditModalDoesNotChangeTheCategory()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelling the edit modal does not change the category", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 181
    await testRunner.GivenAsync("I have created a category \"{unique}\" with color \"#2563EB\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 182
    await testRunner.AndAsync("I open the edit modal for category \"{unique}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table32.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{unique} updated"});
                table32.AddRow(new string[] {
                            ".color-swatch-btn[data-color=\'#EF4444\']",
                            "click",
                            ""});
#line 183
    await testRunner.WhenAsync("fill form", ((string)(null)), table32, "When ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table33.AddRow(new string[] {
                            "#js-close-category-modal"});
#line 187
    await testRunner.AndAsync("click elements", ((string)(null)), table33, "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table34.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 190
    await testRunner.ThenAsync("check elements class", ((string)(null)), table34, "Then ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedCount"});
                table35.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique} updated\')",
                            "0"});
                table35.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\')",
                            "1"});
#line 193
    await testRunner.AndAsync("check elements count", ((string)(null)), table35, "And ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table36.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\') .category-color-dot",
                            "style",
                            "#2563EB"});
#line 197
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table36, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Edit category form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Edit category form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty", "", "#btn-submit-category", "click", "Вкажіть назву категорії", "19", null, DisplayName="Edit category form validation - <Case>(empty,,#btn-submit-category,click,Вкажіть " +
            "назву категорії,19)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("101 chars", "{chars:101}", "#category-name", "blur", "Назва має бути не довше 100 символів", "20", null, DisplayName="Edit category form validation - <Case>(101 chars,{chars:101},#category-name,blur," +
            "Назва має бути не довше 100 символів,20)")]
        public async global::System.Threading.Tasks.Task EditCategoryFormValidation_Case(string @case, string name, string triggerLocator, string triggerAction, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Case", @case);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("TriggerLocator", triggerLocator);
            argumentsOfScenario.Add("TriggerAction", triggerAction);
            argumentsOfScenario.Add("Error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit category form validation - <Case>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 201
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 202
    await testRunner.GivenAsync("I have created a category \"{unique}\" with color \"#2563EB\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 203
    await testRunner.AndAsync("I open the edit modal for category \"{unique}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table37.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            string.Format("{0}", name)});
                table37.AddRow(new string[] {
                            string.Format("{0}", triggerLocator),
                            string.Format("{0}", triggerAction),
                            ""});
#line 204
    await testRunner.WhenAsync("fill form", ((string)(null)), table37, "When ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table38.AddRow(new string[] {
                            "#form-add-category .form-group:has(#category-name) span.form-error-text",
                            "span",
                            "",
                            string.Format("{0}", error)});
#line 208
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table38, "Then ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Enabled"});
                table39.AddRow(new string[] {
                            "#btn-submit-category",
                            "false"});
#line 211
    await testRunner.AndAsync("check elements state", ((string)(null)), table39, "And ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table40.AddRow(new string[] {
                            "#form-add-category",
                            "true"});
#line 214
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table40, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Delete a category and <Action> the confirmation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Delete a category and <Action> the confirmation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Categories page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("accepts", "0", "21", null, DisplayName="Delete a category and <Action> the confirmation(accepts,0,21)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("dismisses", "1", "22", null, DisplayName="Delete a category and <Action> the confirmation(dismisses,1,22)")]
        public async global::System.Threading.Tasks.Task DeleteACategoryAndActionTheConfirmation(string action, string count, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Action", action);
            argumentsOfScenario.Add("Count", count);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete a category and <Action> the confirmation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 227
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 228
    await testRunner.GivenAsync("I open the add category modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table41.AddRow(new string[] {
                            "#category-name",
                            "fill",
                            "{unique}"});
                table41.AddRow(new string[] {
                            "#btn-submit-category",
                            "click",
                            ""});
#line 229
    await testRunner.AndAsync("fill form", ((string)(null)), table41, "And ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table42.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\')",
                            "true"});
#line 233
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table42, "And ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table43.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 236
    await testRunner.AndAsync("check elements class", ((string)(null)), table43, "And ");
#line hidden
#line 239
    await testRunner.AndAsync(string.Format("the browser {0} dialogs", action), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 240
    await testRunner.WhenAsync("click element \"#categories-list .categories-item:has-text(\'{unique}\') .category-d" +
                        "elete-btn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 241
    await testRunner.ThenAsync("a dialog is shown containing \"Видалити цю категорію?\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedCount"});
                table44.AddRow(new string[] {
                            "#categories-list .categories-item:has-text(\'{unique}\')",
                            string.Format("{0}", count)});
#line 242
    await testRunner.AndAsync("check elements count", ((string)(null)), table44, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
