// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UserAuthenticationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "User authentication", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Login.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
    await testRunner.GivenAsync("I am on the auth page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Login.feature.ndjson", 18);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Login panel is shown by default")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login panel is shown by default")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task LoginPanelIsShownByDefault()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login panel is shown by default", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table1.AddRow(new string[] {
                            "#loginPanel",
                            "hidden",
                            "false"});
                table1.AddRow(new string[] {
                            "#registerPanel",
                            "hidden",
                            "true"});
#line 9
    await testRunner.ThenAsync("check elements class", ((string)(null)), table1, "Then ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table2.AddRow(new string[] {
                            "#loginPanel",
                            "true"});
#line 13
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table2, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Toggle link switches between login and register panels")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Toggle link switches between login and register panels")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task ToggleLinkSwitchesBetweenLoginAndRegisterPanels()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Toggle link switches between login and register panels", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.WhenAsync("click element \"#loginPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table3.AddRow(new string[] {
                            "#loginPanel",
                            "hidden",
                            "true"});
                table3.AddRow(new string[] {
                            "#registerPanel",
                            "hidden",
                            "false"});
#line 19
    await testRunner.ThenAsync("check elements class", ((string)(null)), table3, "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table4.AddRow(new string[] {
                            "#registerPanel",
                            "true"});
#line 23
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table4, "And ");
#line hidden
#line 26
    await testRunner.WhenAsync("click element \"#registerPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table5.AddRow(new string[] {
                            "#loginPanel",
                            "hidden",
                            "false"});
                table5.AddRow(new string[] {
                            "#registerPanel",
                            "hidden",
                            "true"});
#line 27
    await testRunner.ThenAsync("check elements class", ((string)(null)), table5, "Then ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table6.AddRow(new string[] {
                            "#loginPanel",
                            "true"});
#line 31
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table6, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Login with invalid credentials shows an error")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login with invalid credentials shows an error")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task LoginWithInvalidCredentialsShowsAnError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login with invalid credentials shows an error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table7.AddRow(new string[] {
                            "#loginEmail",
                            "fill",
                            "wrong@example.com"});
                table7.AddRow(new string[] {
                            "#loginPassword",
                            "fill",
                            "wrongpass"});
                table7.AddRow(new string[] {
                            "#loginForm button[type=submit]",
                            "click",
                            ""});
#line 38
    await testRunner.WhenAsync("fill form", ((string)(null)), table7, "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table8.AddRow(new string[] {
                            "#loginForm .server-error",
                            "true"});
#line 43
    await testRunner.ThenAsync("check elements visibility", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Login form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty email", "loginEmail", "", "Password123!", "Будь ласка, введіть пошту.", "3", null, DisplayName="Login form validation - <Case>(empty email,loginEmail,,Password123!,Будь ласка, в" +
            "ведіть пошту.,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("invalid email", "loginEmail", "not-an-email", "Password123!", "Введіть коректну адресу.", "4", null, DisplayName="Login form validation - <Case>(invalid email,loginEmail,not-an-email,Password123!" +
            ",Введіть коректну адресу.,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty password", "loginPassword", "user@example.com", "", "Будь ласка, введіть пароль.", "5", null, DisplayName="Login form validation - <Case>(empty password,loginPassword,user@example.com,,Буд" +
            "ь ласка, введіть пароль.,5)")]
        public async global::System.Threading.Tasks.Task LoginFormValidation_Case(string @case, string field, string email, string password, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Case", @case);
            argumentsOfScenario.Add("Field", field);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login form validation - <Case>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table9.AddRow(new string[] {
                            "#loginEmail",
                            "fill",
                            string.Format("{0}", email)});
                table9.AddRow(new string[] {
                            "#loginPassword",
                            "fill",
                            string.Format("{0}", password)});
                table9.AddRow(new string[] {
                            "#loginForm button[type=submit]",
                            "click",
                            ""});
#line 49
    await testRunner.WhenAsync("fill form", ((string)(null)), table9, "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table10.AddRow(new string[] {
                            string.Format("label.error[for=\'{0}\']", field),
                            "label",
                            "",
                            string.Format("{0}", error)});
#line 54
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table10, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Register form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Register form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty email", "registerEmail", "", "Password123!", "Будь ласка, введіть пошту.", "6", null, DisplayName="Register form validation - <Case>(empty email,registerEmail,,Password123!,Будь ла" +
            "ска, введіть пошту.,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("invalid email", "registerEmail", "not-an-email", "Password123!", "Введіть коректну адресу електронної пошти.", "7", null, DisplayName="Register form validation - <Case>(invalid email,registerEmail,not-an-email,Passwo" +
            "rd123!,Введіть коректну адресу електронної пошти.,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty password", "registerPassword", "user@example.com", "", "Будь ласка, введіть пароль.", "8", null, DisplayName="Register form validation - <Case>(empty password,registerPassword,user@example.co" +
            "m,,Будь ласка, введіть пароль.,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("too short", "registerPassword", "user@example.com", "Ab1", "Пароль має містити щонайменше 6 символів.", "9", null, DisplayName="Register form validation - <Case>(too short,registerPassword,user@example.com,Ab1" +
            ",Пароль має містити щонайменше 6 символів.,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("no uppercase", "registerPassword", "user@example.com", "password123", "Пароль повинен містити принаймні одну велику літеру, одну малу літеру та одну циф" +
            "ру.", "10", null, DisplayName="Register form validation - <Case>(no uppercase,registerPassword,user@example.com," +
            "password123,Пароль повинен містити принаймні одну велику літеру, одну малу літер" +
            "у та одну цифру.,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("no lowercase", "registerPassword", "user@example.com", "PASSWORD123", "Пароль повинен містити принаймні одну велику літеру, одну малу літеру та одну циф" +
            "ру.", "11", null, DisplayName="Register form validation - <Case>(no lowercase,registerPassword,user@example.com," +
            "PASSWORD123,Пароль повинен містити принаймні одну велику літеру, одну малу літер" +
            "у та одну цифру.,11)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("no digit", "registerPassword", "user@example.com", "Password", "Пароль повинен містити принаймні одну велику літеру, одну малу літеру та одну циф" +
            "ру.", "12", null, DisplayName="Register form validation - <Case>(no digit,registerPassword,user@example.com,Pass" +
            "word,Пароль повинен містити принаймні одну велику літеру, одну малу літеру та од" +
            "ну цифру.,12)")]
        public async global::System.Threading.Tasks.Task RegisterFormValidation_Case(string @case, string field, string email, string password, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Case", @case);
            argumentsOfScenario.Add("Field", field);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register form validation - <Case>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 67
    await testRunner.WhenAsync("click element \"#loginPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table11.AddRow(new string[] {
                            "#registerEmail",
                            "fill",
                            string.Format("{0}", email)});
                table11.AddRow(new string[] {
                            "#registerPassword",
                            "fill",
                            string.Format("{0}", password)});
                table11.AddRow(new string[] {
                            "#registerForm button[type=submit]",
                            "click",
                            ""});
#line 68
    await testRunner.AndAsync("fill form", ((string)(null)), table11, "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table12.AddRow(new string[] {
                            string.Format("label.error[for=\'{0}\']", field),
                            "label",
                            "",
                            string.Format("{0}", error)});
#line 73
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Successful registration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successful registration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task SuccessfulRegistration()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful registration", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.GivenAsync("the browser accepts dialogs", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("click element \"#loginPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table13.AddRow(new string[] {
                            "#registerEmail",
                            "fill",
                            "{uniqueEmail}"});
                table13.AddRow(new string[] {
                            "#registerPassword",
                            "fill",
                            "Password123!"});
                table13.AddRow(new string[] {
                            "#registerForm button[type=submit]",
                            "click",
                            ""});
#line 90
    await testRunner.AndAsync("fill form", ((string)(null)), table13, "And ");
#line hidden
#line 95
    await testRunner.ThenAsync("a dialog is shown containing \"успішна\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table14.AddRow(new string[] {
                            "#loginPanel",
                            "hidden",
                            "false"});
                table14.AddRow(new string[] {
                            "#registerPanel",
                            "hidden",
                            "true"});
#line 96
    await testRunner.AndAsync("check elements class", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Successful registration followed by login")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successful registration followed by login")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task SuccessfulRegistrationFollowedByLogin()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful registration followed by login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 101
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.GivenAsync("the browser accepts dialogs", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
    await testRunner.AndAsync("click element \"#loginPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table15.AddRow(new string[] {
                            "#registerEmail",
                            "fill",
                            "{uniqueEmail}"});
                table15.AddRow(new string[] {
                            "#registerPassword",
                            "fill",
                            "Password123!"});
                table15.AddRow(new string[] {
                            "#registerForm button[type=submit]",
                            "click",
                            ""});
#line 104
    await testRunner.AndAsync("fill form", ((string)(null)), table15, "And ");
#line hidden
#line 109
    await testRunner.AndAsync("a dialog is shown containing \"успішна\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table16.AddRow(new string[] {
                            "#loginEmail",
                            "fill",
                            "{uniqueEmail}"});
                table16.AddRow(new string[] {
                            "#loginPassword",
                            "fill",
                            "Password123!"});
                table16.AddRow(new string[] {
                            "#loginForm button[type=submit]",
                            "click",
                            ""});
#line 110
    await testRunner.WhenAsync("fill form", ((string)(null)), table16, "When ");
#line hidden
#line 115
    await testRunner.ThenAsync("the current path is \"/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Registration with an already used email shows an error")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Registration with an already used email shows an error")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User authentication")]
        public async global::System.Threading.Tasks.Task RegistrationWithAnAlreadyUsedEmailShowsAnError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registration with an already used email shows an error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 118
    await testRunner.GivenAsync("a user is already registered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 119
    await testRunner.AndAsync("the browser accepts dialogs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.WhenAsync("click element \"#loginPanel .toggle-auth-panels\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table17.AddRow(new string[] {
                            "#registerEmail",
                            "fill",
                            "{uniqueEmail}"});
                table17.AddRow(new string[] {
                            "#registerPassword",
                            "fill",
                            "Password123!"});
                table17.AddRow(new string[] {
                            "#registerForm button[type=submit]",
                            "click",
                            ""});
#line 121
    await testRunner.AndAsync("fill form", ((string)(null)), table17, "And ");
#line hidden
#line 126
    await testRunner.ThenAsync("no dialog is shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table18.AddRow(new string[] {
                            "label.error[for=\'registerEmail\']",
                            "label",
                            "",
                            ""});
#line 127
    await testRunner.AndAsync("check elements existence", ((string)(null)), table18, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
