// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class SettingsPageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Settings page", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Settings.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
    await testRunner.GivenAsync("I am logged in and on the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Settings.feature.ndjson", 16);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Settings page is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Settings page is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task SettingsPageIsDisplayed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Settings page is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table1.AddRow(new string[] {
                            ".settings-header h1",
                            "h1",
                            "",
                            "Налаштування організації"});
                table1.AddRow(new string[] {
                            ".settings-organization",
                            "div",
                            "",
                            ""});
                table1.AddRow(new string[] {
                            ".settings-organization-body h2",
                            "h2",
                            "",
                            ""});
                table1.AddRow(new string[] {
                            ".settings-members-list",
                            "div",
                            "",
                            ""});
                table1.AddRow(new string[] {
                            "#open-invite-member-modal-btn",
                            "button",
                            "",
                            ""});
                table1.AddRow(new string[] {
                            "#open-delete-organization-dialog",
                            "button",
                            "",
                            ""});
#line 9
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table1, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Current user is shown in the members list as owner")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Current user is shown in the members list as owner")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task CurrentUserIsShownInTheMembersListAsOwner()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Current user is shown in the members list as owner", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table2.AddRow(new string[] {
                            ".settings-member:has-text(\'newuser@example.com\') .settings-pill",
                            "span",
                            "",
                            "Ви"});
                table2.AddRow(new string[] {
                            ".settings-member:has-text(\'newuser@example.com\') .settings-role",
                            "span",
                            "",
                            "Owner"});
#line 21
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table2, "Then ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table3.AddRow(new string[] {
                            ".settings-member:has-text(\'newuser@example.com\') .settings-role",
                            "is-owner",
                            "true"});
#line 25
    await testRunner.AndAsync("check elements class", ((string)(null)), table3, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Open and close the invite member modal")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Open and close the invite member modal")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task OpenAndCloseTheInviteMemberModal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Open and close the invite member modal", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table4.AddRow(new string[] {
                            "#open-invite-member-modal-btn"});
#line 32
    await testRunner.WhenAsync("click elements", ((string)(null)), table4, "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table5.AddRow(new string[] {
                            "#form-invite-member",
                            "true"});
#line 35
    await testRunner.ThenAsync("check elements visibility", ((string)(null)), table5, "Then ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table6.AddRow(new string[] {
                            "#js-close-invite-member-modal"});
#line 38
    await testRunner.WhenAsync("click elements", ((string)(null)), table6, "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table7.AddRow(new string[] {
                            "#app-modal",
                            "is-active",
                            "false"});
#line 41
    await testRunner.ThenAsync("check elements class", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Invite member form defaults")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invite member form defaults")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task InviteMemberFormDefaults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invite member form defaults", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("I open the invite member modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedValue"});
                table8.AddRow(new string[] {
                            "#member-email",
                            ""});
                table8.AddRow(new string[] {
                            "#member-role",
                            "accountant"});
#line 47
    await testRunner.ThenAsync("check elements value", ((string)(null)), table8, "Then ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ExpectedCount"});
                table9.AddRow(new string[] {
                            "#member-role option",
                            "3"});
#line 51
    await testRunner.AndAsync("check elements count", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Invite member form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invite member form validation - <Case>")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("empty", "", "#btn-submit-invite-member", "click", "Вкажіть email користувача", "4", null, DisplayName="Invite member form validation - <Case>(empty,,#btn-submit-invite-member,click,Вка" +
            "жіть email користувача,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("no at sign", "not-an-email", "#member-email", "blur", "Введіть коректний email", "5", null, DisplayName="Invite member form validation - <Case>(no at sign,not-an-email,#member-email,blur" +
            ",Введіть коректний email,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("no domain", "user@", "#member-email", "blur", "Введіть коректний email", "6", null, DisplayName="Invite member form validation - <Case>(no domain,user@,#member-email,blur,Введіть" +
            " коректний email,6)")]
        public async global::System.Threading.Tasks.Task InviteMemberFormValidation_Case(string @case, string email, string triggerLocator, string triggerAction, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Case", @case);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("TriggerLocator", triggerLocator);
            argumentsOfScenario.Add("TriggerAction", triggerAction);
            argumentsOfScenario.Add("Error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invite member form validation - <Case>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("I open the invite member modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table10.AddRow(new string[] {
                            "#member-email",
                            "fill",
                            string.Format("{0}", email)});
                table10.AddRow(new string[] {
                            string.Format("{0}", triggerLocator),
                            string.Format("{0}", triggerAction),
                            ""});
#line 61
    await testRunner.WhenAsync("fill form", ((string)(null)), table10, "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table11.AddRow(new string[] {
                            "#form-invite-member .form-group:has(#member-email) span.form-error-text",
                            "span",
                            "",
                            string.Format("{0}", error)});
#line 65
    await testRunner.ThenAsync("check elements existence", ((string)(null)), table11, "Then ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Enabled"});
                table12.AddRow(new string[] {
                            "#btn-submit-invite-member",
                            "false"});
#line 68
    await testRunner.AndAsync("check elements state", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table13.AddRow(new string[] {
                            "#form-invite-member",
                            "true"});
#line 71
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table13, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Valid email passes validation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Valid email passes validation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task ValidEmailPassesValidation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Valid email passes validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 82
    await testRunner.GivenAsync("I open the invite member modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table14.AddRow(new string[] {
                            "#member-email",
                            "fill",
                            "user@example.com"});
                table14.AddRow(new string[] {
                            "#member-email",
                            "blur",
                            ""});
#line 83
    await testRunner.WhenAsync("fill form", ((string)(null)), table14, "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Enabled"});
                table15.AddRow(new string[] {
                            "#btn-submit-invite-member",
                            "true"});
#line 87
    await testRunner.ThenAsync("check elements state", ((string)(null)), table15, "Then ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table16.AddRow(new string[] {
                            "#form-invite-member .form-group:has(#member-email) span.form-error-text",
                            "false"});
#line 90
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table16, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Successfully invite an existing user")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successfully invite an existing user")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task SuccessfullyInviteAnExistingUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully invite an existing user", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 99
    await testRunner.GivenAsync("I open the invite member modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Action",
                            "Value"});
                table17.AddRow(new string[] {
                            "#member-email",
                            "fill",
                            "member@example.com"});
                table17.AddRow(new string[] {
                            "#btn-submit-invite-member",
                            "click",
                            ""});
#line 100
    await testRunner.WhenAsync("fill form", ((string)(null)), table17, "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table18.AddRow(new string[] {
                            ".settings-member:has-text(\'member@example.com\')",
                            "true"});
#line 104
    await testRunner.ThenAsync("check elements visibility", ((string)(null)), table18, "Then ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table19.AddRow(new string[] {
                            ".settings-member:has-text(\'member@example.com\') .settings-role",
                            "span",
                            "",
                            "Member"});
#line 107
    await testRunner.AndAsync("check elements existence", ((string)(null)), table19, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Open the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Open the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task OpenTheDeleteOrganizationDialog()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Open the delete organization dialog", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table20.AddRow(new string[] {
                            "#open-delete-organization-dialog"});
#line 116
    await testRunner.WhenAsync("click elements", ((string)(null)), table20, "When ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table21.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "is-active",
                            "true"});
#line 119
    await testRunner.ThenAsync("check elements class", ((string)(null)), table21, "Then ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table22.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "aria-hidden",
                            "false"});
#line 122
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ElementTagName",
                            "AttributeName",
                            "ElementValue"});
                table23.AddRow(new string[] {
                            "#delete-organization-title",
                            "h2",
                            "",
                            "Видалити організацію?"});
#line 125
    await testRunner.AndAsync("check elements existence", ((string)(null)), table23, "And ");
#line hidden
#line 128
    await testRunner.AndAsync("the delete organization dialog mentions the organization name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cancel closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cancel closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task CancelClosesTheDeleteOrganizationDialog()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancel closes the delete organization dialog", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 131
    await testRunner.GivenAsync("I open the delete organization dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator"});
                table24.AddRow(new string[] {
                            "#cancel-delete-organization"});
#line 132
    await testRunner.WhenAsync("click elements", ((string)(null)), table24, "When ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table25.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "is-active",
                            "false"});
#line 135
    await testRunner.ThenAsync("check elements class", ((string)(null)), table25, "Then ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "AttributeName",
                            "ExpectedValue"});
                table26.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "aria-hidden",
                            "true"});
#line 138
    await testRunner.AndAsync("check elements attribute contains", ((string)(null)), table26, "And ");
#line hidden
#line 141
    await testRunner.AndAsync("current url contains \"/settings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "Visible"});
                table27.AddRow(new string[] {
                            ".settings-organization",
                            "true"});
#line 142
    await testRunner.AndAsync("check elements visibility", ((string)(null)), table27, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Escape closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Escape closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task EscapeClosesTheDeleteOrganizationDialog()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Escape closes the delete organization dialog", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 146
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 147
    await testRunner.GivenAsync("I open the delete organization dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
    await testRunner.WhenAsync("I press the Escape key", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table28.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "is-active",
                            "false"});
#line 149
    await testRunner.ThenAsync("check elements class", ((string)(null)), table28, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Clicking the overlay closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Clicking the overlay closes the delete organization dialog")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task ClickingTheOverlayClosesTheDeleteOrganizationDialog()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking the overlay closes the delete organization dialog", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 153
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 154
    await testRunner.GivenAsync("I open the delete organization dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 155
    await testRunner.WhenAsync("I click outside the delete organization dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table29.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "is-active",
                            "false"});
#line 156
    await testRunner.ThenAsync("check elements class", ((string)(null)), table29, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Clicking inside the delete organization dialog keeps it open")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Clicking inside the delete organization dialog keeps it open")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Settings page")]
        public async global::System.Threading.Tasks.Task ClickingInsideTheDeleteOrganizationDialogKeepsItOpen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking inside the delete organization dialog keeps it open", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 160
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 161
    await testRunner.GivenAsync("I open the delete organization dialog", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 162
    await testRunner.WhenAsync("click element \"#delete-organization-title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "ElementLocator",
                            "ClassName",
                            "HasClass"});
                table30.AddRow(new string[] {
                            "#delete-organization-dialog",
                            "is-active",
                            "true"});
#line 163
    await testRunner.ThenAsync("check elements class", ((string)(null)), table30, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
